### ISSUE TITLE
不支持GitHub-pages？

### ISSUE THREAD

**Issue by mhcn** [erlzhang/jekyll-theme-arktos#1]
不支持GitHub-pages？push上去github发邮件说不支持这个主题。有碰到这个问题吗？

**Comment by erlzhang** [comment]
github-pages 仅支持有限的主题，可以通过 `remote_theme` 使用：

`remote_theme: erlzhang/jekyll-theme-arktos`

详细的可以参考我的 [demo](https://github.com/erlzhang/arktos-demo/blob/master/_config.yml) 配置。
